name: Basic Workflow

on: [push]

jobs:
  hello:
    runs-on: Sapir-PC
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "Hello, World!"
